In [1]:
a=1

In [3]:
a

1

In [4]:
a=10

In [5]:
a

10

In [6]:
for i in range(1,10)

SyntaxError: invalid syntax (182340526.py, line 1)

In [7]:
for i in range(1,10):


SyntaxError: unexpected EOF while parsing (1468085492.py, line 1)

In [1]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [2]:
for i in range(6):
    for j in range(i+1):
        print("*",end="")
    print()

*
**
***
****
*****
******


In [3]:
for i in range(5):
    for j in range(1,n-i):
        print(" ",end="")
    for k in range(i+1):
        print("*",end="")
    print()

NameError: name 'n' is not defined

In [4]:
for i in range(5):
    for j in range(1,5-i):
        print(" ",end="")
    for k in range(i+1):
        print("*",end="")
    print()

    *
   **
  ***
 ****
*****


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np
print(np.__version__)

1.22.3


# numpy


In [9]:
b=np.array([[1,2,3],[1,2,3]])
print(b,type(b))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [10]:
print(b.ndim)
b.shape

2


(2, 3)

In [11]:
a=np.array([[[1,2,3],[1,2,3],[3,2,5]]])
print(a,type(a))

[[[1 2 3]
  [1 2 3]
  [3 2 5]]] <class 'numpy.ndarray'>


In [12]:
print(a.ndim)

3


In [13]:
#zeros()
b=np.zeros((5))
print(b)

[0. 0. 0. 0. 0.]


In [18]:
b=np.zeros((5,2,3))
print(b.ndim)
b

3


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
a=np.eye(5,k=2)
print(a)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
a=np.eye(5,k=-2)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [24]:
a=np.random.randn(5,5)
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)

[[ 0.82588411 -1.00271153 -0.03364598 -1.06836976 -0.11835295]
 [-0.94318012  1.93913054 -1.05134214 -0.22253741  0.0727995 ]
 [-1.19699675  0.99346053  0.6262641   0.77353057  1.39408316]
 [ 0.60543317  0.08710547 -1.11446322 -2.37562199 -0.4565315 ]
 [ 0.69179829 -0.1485652   0.70529379  1.15109231 -1.08356438]]
2
float64
(5, 5)
25


In [25]:
import random
z=random.random()
z

0.14003151917129764

In [30]:
#properties of array
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3,],[1,2,3]],[[1,2,3],[1,2,3]]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3
int64
(3, 2, 3)
18


In [31]:
#copy()
a=np.array([1,2,3])
x=a.copy()
x[0]=10
print("original values",a)
print("copy values",x)
print("*"*30)
#view()
a=np.array([1,2,3])
y=a.view()
y[0]=10
print("original values",a)
print("view values",y)

original values [1 2 3]
copy values [10  2  3]
******************************
original values [10  2  3]
view values [10  2  3]


In [46]:
#array operations
a=np.array([1,2,3])
print("original",a)
print("single dimensional")
b=np.append(a,[4,5,6])
print('second array',b)
print("*"*40)

a=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("2 dimensional array",a)
print("*"*40)

b=np.append(a,[[4,5,6,7],[1,2,3,4],[4,5,6,7]])
print("after horizontal append with 1 dimensional:")
print(b)
print("*"*40)

c=np.append(a,[[4,5,6,4],[1,2,3,5],[4,5,6,7]],axis=1)
print("axis 1 positional:")
print(c)

d=np.append(a,[[4,5,6],[1,2,3],[4,5,6]],axis=0)
print("axis 0 positonal")
print(d)

original [1 2 3]
single dimensional
second array [1 2 3 4 5 6]
****************************************
2 dimensional array [[1 2 3]
 [1 2 3]
 [1 2 3]]
****************************************
after horizontal append with 1 dimensional:
[1 2 3 1 2 3 1 2 3 4 5 6 7 1 2 3 4 4 5 6 7]
****************************************
axis 1 positional:
[[1 2 3 4 5 6 4]
 [1 2 3 1 2 3 5]
 [1 2 3 4 5 6 7]]
axis 0 positonal
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [47]:
#insert
a=np.array([1,2,3])
print(a)
b=np.insert(a,0,4)
print("after insert",b)

[1 2 3]
after insert [4 1 2 3]


In [48]:
#delete
a=np.array([[1,2,3],[11,22,33],[21,24,25]])
print(a)
c=np.delete(a,4)
print(c)
d=np.delete(a,[1,4,7])
print(d)

[[ 1  2  3]
 [11 22 33]
 [21 24 25]]
[ 1  2  3 11 33 21 24 25]
[ 1  3 11 33 21 25]


In [49]:
list1=[2,3,4]
list2=[3,5,6]
print(list1+list2)

[2, 3, 4, 3, 5, 6]


In [50]:
a=np.array([1,2,4])
aa=np.array([4,5,6])
c=a+aa
c

array([ 5,  7, 10])